### ISSUE TITLE
ReflectionType::__toString() is deprecated. It fails in PHP7.4

### ISSUE THREAD

**Issue by arnedesmedt** [event-engine/php-data#1]
https://github.com/event-engine/php-data/blob/97699d9bbce7b6bb65aa919c9f0a6da011bb3955/src/ImmutableRecordLogic.php#L302

https://www.php.net/manual/en/reflectiontype.tostring.php

You can get the name from the https://www.php.net/manual/en/class.reflectionnamedtype.php
But I don't have any idea how to retrieve that object from the ReflectionMethod? Do you guys knows how to solve this problem?

**Comment by codeliner** [comment]
I'd like to refactor `ImmutableRecordLogic` to use the new typed properties feature of PHP 7.4 instead of deriving the type from the return type of a getter method. 

Not sure yet, if this should become a new major version of the package, that only works with PHP 7.4+ or if we can check the PHP version internally and switch between strategies to collect type information.

**Comment by codeliner** [comment]
My time is limited at the moment. If you or someone else wants to work on this, I'd be more than happy ;). If possible, I'd prefer checking the PHP version.
